### ISSUE TITLE
Extra Points

### ISSUE THREAD

**Issue by alexanderschoenberger** [htl-perg-2019-20-5ahif/travel-planner-api-alexanderschoenberger#1]
Also added extra requirements

**Comment by rstropek** [comment]
Nearly. Please use `IHttpClientFactory` in ASP.NET Core apps to get an instance of `HttpClient` (see [this slide](http://htl-mobile-computing-5.azurewebsites.net/#/6/1) and [this video](https://youtu.be/hj0joKgs01c?t=2512)). Fix that and the two extra points will be yours.

**Comment by alexanderschoenberger** [comment]
Fixed
